openapi: 3.0.0
info:
  title: funding-service
  version: 1.0.0
servers:
  - url: https://api.dev.halth.com
components:
  schemas: {}
  parameters: {}
paths:
  /funding/au/service-items:
    get:
      tags:
        - Item codes
      summary: Get item codes
      description: List all available item codes
      responses:
        "200":
          description: Item codes
  /funding/au/health-funds:
    get:
      tags:
        - Health Funds
      description: List all available health funds
      summary: Get health funds
      responses:
        "200":
          description: Health funds
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    enum: &a1
                      - AHM
                      - ACA
                      - AUNITY
                      - BUPA
                      - CBHS
                      - NAVY
                      - PEOPLE
                      - TEACH
                      - UNI
                      - GMHBA
                      - FRANK
                      - BUDGET
                      - NIB
                      - AAMI
                      - APIA
                      - QANTAS
                      - SUN
                      - HIWA
                      - DEFH
                      - ONEMED
                      - SEEU
                      - WEST
                      - LATRO
                      - HBF
                      - RT
                      - TUH
                      - UNION
                      - POLICE
                      - PHNX
                      - CBHSC
                      - ADF
                      - HPART
                      - STLUK
                      - ASTUTE
                      - RBHS
                      - DOC
                      - HCI
                      - TEST
                      - HCF
                      - MEDIB
                      - QCH
                      - TERR
                  displayName:
                    type: string
                required:
                  - id
                  - displayName
              example:
                id: BUPA
                displayName: Bupa
  /funding/au/health-fund-cards:
    post:
      tags:
        - Health Fund Cards
      summary: Create health fund card
      description:
        Construct a digital copy of a health fund card. The requirements
        for each health fund will vary.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                memberNumber:
                  type: string
                  minLength: 1
                  maxLength: 16
                issueNumber:
                  type: string
                  minLength: 1
                  maxLength: 3
                healthFundId:
                  type: string
                  enum: *a1
                cardholders:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                        minLength: 1
                        maxLength: 255
                      referenceNumber:
                        type: string
                        minLength: 1
                        maxLength: 2
                    required:
                      - name
                      - referenceNumber
                defaultReferenceNumber:
                  type: string
                  minLength: 1
                  maxLength: 3
                issueDate:
                  type: string
                  format: date
              required:
                - memberNumber
                - healthFundId
            example:
              healthFundId: AHM
              memberNumber: "123456789"
              referenceNumber: "01"
              issueNumber: "1"
      responses:
        "201":
          description: Health fund card created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  memberNumberLast4:
                    type: string
                  healthFundId:
                    type: string
                    enum: *a1
                  healthFund:
                    type: object
                    properties:
                      id:
                        type: string
                        enum: *a1
                      displayName:
                        type: string
                    required:
                      - id
                      - displayName
                  cardholders:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                          minLength: 1
                          maxLength: 255
                        referenceNumber:
                          type: string
                          minLength: 1
                          maxLength: 2
                      required:
                        - name
                        - referenceNumber
                  fingerprint:
                    type: string
                  defaultReferenceNumber:
                    type: string
                required:
                  - id
                  - memberNumberLast4
                  - healthFundId
                  - healthFund
                  - cardholders
                  - fingerprint
              example:
                id: hfcd_2wg8XkT3hmR7ll3zn4JqWt1HHTV
                memberNumberLast4: "4321"
                healthFundId: BUPA
                healthFund:
                  id: BUPA
                  displayName: Bupa
                cardholders: []
                fingerprint: badb30513613e35870fef3b8a1ca3b368b11ad097d9997350a71dfb9f2396b05
                defaultReferenceNumber: "01"
  /funding/au/quotes:
    post:
      tags:
        - Quotes
      summary: Create funding quote
      description: Check for funding eligibility with a given provider and service
      requestBody:
        required: true
        description: Create a funding quote
        content:
          application/json:
            schema:
              type: object
              properties:
                serviceProvider:
                  type: object
                  properties:
                    locationId:
                      type: string
                    providerId:
                      type: string
                  required:
                    - locationId
                    - providerId
                transactionItems:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        description: Unique identifier for the transaction item
                        example: "1"
                      chargeAmount:
                        anyOf:
                          - type: number
                            enum:
                              - 0
                          - type: integer
                            minimum: 0
                            maximum: 9999999
                            description: Charge amount in cents
                            example: 10005
                      itemCode:
                        type: string
                      description:
                        type: string
                      clinicalCode:
                        type: string
                      isICDCode:
                        type: boolean
                    required:
                      - chargeAmount
                      - description
                phi:
                  type: object
                  properties:
                    healthFundCardId:
                      type: string
                    patient:
                      type: object
                      properties:
                        referenceNumber:
                          type: string
                        location:
                          type: object
                          properties:
                            longitude:
                              type: number
                            latitude:
                              type: number
                            altitude:
                              type: number
                            accuracy:
                              type: number
                          required:
                            - longitude
                            - latitude
                  required:
                    - healthFundCardId
              required:
                - serviceProvider
                - transactionItems
            example:
              serviceProvider:
                locationId: loc_2wg8XkT3hmR7ll3zn4JqWt1HHTV
                providerId: prov_2wg8XkT3hmR7ll3zn4JqWt1HHTV
              healthFundCardId: hfcd_2wg8XkT3hmR7ll3zn4JqWt1HHTV
              transactionItems:
                - itemCode: "1002"
                  description: Chiropractic adjustment
                  chargeAmount: 9300
      responses:
        "200":
          description: Funding quote
